// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:767185697219:web:YOUR_APP_ID',
    messagingSenderId: '767185697219',
    projectId: 'balletplus-519b5',
    authDomain: 'balletplus-519b5.firebaseapp.com',
    storageBucket: 'balletplus-519b5.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf7cnR-S7Vf7zw2rq3ox7ptJ9rMcDd46w',
    appId: '1:767185697219:android:39bbfdc3684afb79d52576',
    messagingSenderId: '767185697219',
    projectId: 'balletplus-519b5',
    storageBucket: 'balletplus-519b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJh7QhV6x4LmmGmq-5vTNkz-bPC8qW-t0',
    appId: '1:767185697219:ios:a45818dce913e3bfd52576',
    messagingSenderId: '767185697219',
    projectId: 'balletplus-519b5',
    storageBucket: 'balletplus-519b5.firebasestorage.app',
    iosBundleId: 'com.accu.balletPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:767185697219:ios:YOUR_APP_ID',
    messagingSenderId: '767185697219',
    projectId: 'balletplus-519b5',
    storageBucket: 'balletplus-519b5.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'com.accu.balletPlus.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: '1:767185697219:web:YOUR_APP_ID',
    messagingSenderId: '767185697219',
    projectId: 'balletplus-519b5',
    authDomain: 'balletplus-519b5.firebaseapp.com',
    storageBucket: 'balletplus-519b5.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );
}